### ISSUE TITLE
Need gradle guide for instrumentation in eclipse IDE

### ISSUE THREAD

**Issue by mac10046** [javalite/simple-example#6]
Hi

I am using gradlew in my project and eclipse - oxygen, wish to know how can I do the instrumentation using gradle and setup the eclipse IDE as well ?

Something Similer to maven - as explained here
https://github.com/javalite/simple-example#instrumentation

Thanks

**Comment by mac10046** [comment]
found it out http://javalite.io/instrumentation

**Comment by mac10046** [comment]
Although I found the documentation and tried everything written in it. I could not compile the plugin provided.

If possible please provide a sample project for gradlew and eclipse setup.

Thanks

**Comment by ipolevoy** [comment]
Please, see https://github.com/javalite/activejdbc-gradle
